# The location where the database will be stored.
recipesDb: ./dist/recipes.db

# The location where the JSON recipes are stored.
recipesDir: ./dist/recipes

host: "localhost"
port: 3001

# The duration in seconds for which the server
# gracefully waits for existing connections to finish.
wait: 10

# The interval at which the recipes database will be indexed.
# A value of -1 will disable the automatic indexing.
# The syntax is [int][unit], e.g. 10m, 1h, 1d.
# Valid units are:
#   - m: minutes
#   - h: hours
#   - d: days
#   - M: months
#   - w: weeks
#   - y: years
indexInterval: 1d

# Your FoodData Central API key.
#
# To get a key:
# 1. Sign up on https://fdc.nal.usda.gov/api-key-signup.html
# 2. Copy the key here
fdcApiKey: 8v2PniYQdZm5Tz5wTSviVUfN503LUg47TvLHXDxD
